/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Logica.Collaborator;
import Logica.Payroll;
import Logica.Plus;
import Logica.PlusCollaborator;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manyor
 */
public class frmPayroll extends javax.swing.JInternalFrame {

    ArrayList<Collaborator> collaboratorArrayList;
    ArrayList<Payroll> payrollArrayList;
    ArrayList<PlusCollaborator> plusCollArrayList;
    ArrayList<Plus> plusArrayList;
    DefaultTableModel temp;
    String titulos[] = {"PAYROLL ID", "CREATION DATE", "MONTH", "PAY DATE", "EMPLOYEE", "BASE SALARY", "TOTAL PLUS", " TOTAL SALARY", "CCSS", "BP", "NET SALARY"};
    String months[] = {"Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"};
    DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
    DefaultComboBoxModel comboModelYears = new DefaultComboBoxModel();
    frmQueryPayroll queryPayroll = new frmQueryPayroll();

    /**
     * Creates new form frmPayroll
     */
    public frmPayroll() {
        initComponents();
    }

    public frmPayroll(frmMain aThis, ArrayList<Collaborator> collArrayList, ArrayList<Payroll> payArrayList, ArrayList<Plus> plusArrayList, ArrayList<PlusCollaborator> plusesCollaborator) {
        initComponents();
        this.collaboratorArrayList = collArrayList;
        this.payrollArrayList = payArrayList;
        this.plusArrayList = plusArrayList;
        this.plusCollArrayList = plusesCollaborator;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dtpCurrentDate = new org.jdesktop.swingx.JXDatePicker();
        DtpPaymentDate = new org.jdesktop.swingx.JXDatePicker();
        btnGeneratePayroll = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        cmbSearch = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPayroll = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnShowPreview = new javax.swing.JButton();
        cmbMonth = new javax.swing.JComboBox<>();
        cmbYears = new javax.swing.JComboBox<>();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Generate Payroll"));

        jLabel1.setText("Current Date:");

        jLabel2.setText("Payment date:");

        dtpCurrentDate.setEditable(false);

        btnGeneratePayroll.setText("Generate");
        btnGeneratePayroll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGeneratePayrollActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DtpPaymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(dtpCurrentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGeneratePayroll, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dtpCurrentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGeneratePayroll))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(DtpPaymentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jLabel3.setText("Search:");

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        cmbSearch.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IdPayroll", "IdCollaborator" }));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel3)
                .addGap(38, 38, 38)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21)
                .addComponent(cmbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(447, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tblPayroll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblPayroll);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Payroll Check"));

        btnShowPreview.setText("Preview");
        btnShowPreview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowPreviewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(137, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(cmbMonth, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbYears, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnShowPreview, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(73, 73, 73))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmbMonth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbYears, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnShowPreview)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(17, 17, 17))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:

    }//GEN-LAST:event_formInternalFrameActivated

   
    private void btnGeneratePayrollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGeneratePayrollActionPerformed
        // TODO add your handling code here:
        if (DtpPaymentDate.getDate() != null) {
            if (DtpPaymentDate.getDate().compareTo(dtpCurrentDate.getDate()) > 0) {
                String month[] = DtpPaymentDate.getDate().toString().split(" ");
                if (!verifyPayroll(month[1])) {
                    for (int i = 0; i < collaboratorArrayList.size(); i++) {
                        Payroll PayrollObj = new Payroll(successiveNumber(), dtpCurrentDate.getDate(), month[1],
                                DtpPaymentDate.getDate(), collaboratorArrayList.get(i), collaboratorArrayList.get(i).getPosition().getSalary(),
                                getPlus(collaboratorArrayList.get(i)), getTotalsalary(collaboratorArrayList.get(i)),
                                getCCSS(collaboratorArrayList.get(i)), getBP(collaboratorArrayList.get(i)), getNetSalary(collaboratorArrayList.get(i)));
                        payrollArrayList.add(PayrollObj);
                        cleanFields();
                        fillTable();
                    }
                } else {
                    JOptionPane.showConfirmDialog(this, "Payroll already exist for this Month " + month[1], "Confirm Message", JOptionPane.DEFAULT_OPTION);
                }
            } else {

                JOptionPane.showConfirmDialog(this, "Invalid payment date, please check", "Confirm Message", JOptionPane.DEFAULT_OPTION);
            }

        } else {

            JOptionPane.showConfirmDialog(this, "Please, Complete required information", "Confirm Message", JOptionPane.DEFAULT_OPTION);
        }
    }//GEN-LAST:event_btnGeneratePayrollActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        Date fecha = new Date();
        dtpCurrentDate.setDate(fecha);
        int year = 2015;
        for (String month : months) {
            comboBoxModel.addElement(month);
        }

        for (int i = 0; i < 15; i++) {

            comboModelYears.addElement(year++);
        }
        cmbMonth.setModel(comboBoxModel);
        cmbYears.setModel(comboModelYears);
        fillTable();

    }//GEN-LAST:event_formInternalFrameOpened

    private void btnShowPreviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowPreviewActionPerformed
        // TODO add your handling code here:
        if (!queryPayroll.isShowing()) {
            queryPayroll = new frmQueryPayroll(this, payrollArrayList, Integer.parseInt(cmbYears.getSelectedItem().toString()), cmbMonth.getSelectedItem().toString());
            queryPayroll.setTitle(title);
            frmMain.dkpPrincipal.add(queryPayroll);
            queryPayroll.toFront();
            queryPayroll.setVisible(true);
        } else {
            queryPayroll.moveToFront();
        }


    }//GEN-LAST:event_btnShowPreviewActionPerformed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        temp = new DefaultTableModel(null, titulos);

        for (int i = 0; i < payrollArrayList.size(); i++) {
            switch (cmbSearch.getSelectedIndex()) {
                case 0:
                    if (String.valueOf(payrollArrayList.get(i).getIdPayroll()).contains(txtSearch.getText())) {

                        temp.addRow(new Object[]{payrollArrayList.get(i).getIdPayroll(), payrollArrayList.get(i).getCreatrionDate(), payrollArrayList.get(i).getPayDate(),
                            payrollArrayList.get(i).getMonth(), payrollArrayList.get(i).getIdCollaborator().getDNI(),
                            payrollArrayList.get(i).getIdCollaborator().getPosition().getSalary(), payrollArrayList.get(i).getTotalPlus(), payrollArrayList.get(i).getTotalSalary(),
                            payrollArrayList.get(i).getDeductionsCCSS(), payrollArrayList.get(i).getDeductionsBP(), payrollArrayList.get(i).getNetSalary()});

                    }
                    break;
                case 1:
                    System.out.println(String.valueOf(payrollArrayList.get(i).getIdCollaborator().getDNI()));
                    if (String.valueOf(payrollArrayList.get(i).getIdCollaborator().getDNI()).contains(txtSearch.getText())) {
                        temp.addRow(new Object[]{payrollArrayList.get(i).getIdPayroll(), payrollArrayList.get(i).getCreatrionDate(), payrollArrayList.get(i).getPayDate(),
                            payrollArrayList.get(i).getMonth(), payrollArrayList.get(i).getIdCollaborator().getDNI(),
                            payrollArrayList.get(i).getIdCollaborator().getPosition().getSalary(), payrollArrayList.get(i).getTotalPlus(), payrollArrayList.get(i).getTotalSalary(),
                            payrollArrayList.get(i).getDeductionsCCSS(), payrollArrayList.get(i).getDeductionsBP(), payrollArrayList.get(i).getNetSalary()});

                    }
                    break;

            }
        }
        tblPayroll.setModel(temp);
    }//GEN-LAST:event_txtSearchKeyReleased

    private void fillTable() {
        if (payrollArrayList.size() > 0) {
            temp = new DefaultTableModel(null, titulos);
            for (int i = 0; i < payrollArrayList.size(); i++) {

                temp.addRow(new Object[]{payrollArrayList.get(i).getIdPayroll(), payrollArrayList.get(i).getCreatrionDate(), payrollArrayList.get(i).getPayDate(),
                    payrollArrayList.get(i).getMonth(), payrollArrayList.get(i).getIdCollaborator().getDNI(),
                    payrollArrayList.get(i).getIdCollaborator().getPosition().getSalary(), payrollArrayList.get(i).getTotalPlus(), payrollArrayList.get(i).getTotalSalary(),
                    payrollArrayList.get(i).getDeductionsCCSS(), payrollArrayList.get(i).getDeductionsBP(), payrollArrayList.get(i).getNetSalary()});
            }
            this.tblPayroll.setModel(temp);
        }

    }

    public int successiveNumber() {
        return payrollArrayList.size() + 1;
    }

    public double getNetSalary(Collaborator coll) {
        double deduc = getBP(coll) + getCCSS(coll);
        return getPlus(coll) + (getTotalsalary(coll) - deduc);
    }

    public double getBP(Collaborator coll) {

        return (coll.getPosition().getSalary() * 10) / 100;
    }

    public double getCCSS(Collaborator coll) {

        return (coll.getPosition().getSalary() * 13) / 100;
    }

    public double getTotalsalary(Collaborator coll) {

        return getPlus(coll) + coll.getPosition().getSalary();
    }

    public double getPlus(Collaborator coll) {
        double totalPlus = 0;
        for (int i = 0; i < plusCollArrayList.size(); i++) {
            int collaborator = plusCollArrayList.get(i).getIdCollaborator().getDNI();
            int plus = plusCollArrayList.get(i).getIdPlus().getIdPlus();
            for (int j = 0; j < plusArrayList.size(); j++) {
                if (collaborator == coll.getDNI() && plus == plusArrayList.get(i).getIdPlus()) {
                    totalPlus += (coll.getPosition().getSalary() * plusArrayList.get(i).getPercIncrement()) / 100;
                }

            }
        }
        return totalPlus;
    }

    public boolean verifyPayroll(String month) {
        for (int i = 0; i < payrollArrayList.size(); i++) {
            if (month.equals(payrollArrayList.get(i).getMonth())) {
                return true;
            }
        }

        return false;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXDatePicker DtpPaymentDate;
    private javax.swing.JButton btnGeneratePayroll;
    private javax.swing.JButton btnShowPreview;
    private javax.swing.JComboBox<String> cmbMonth;
    private javax.swing.JComboBox<String> cmbSearch;
    private javax.swing.JComboBox<String> cmbYears;
    private org.jdesktop.swingx.JXDatePicker dtpCurrentDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPayroll;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables

    private void cleanFields() {
    }
}
