/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Logica.Payroll;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Manyor
 */
public class frmQueryPayroll extends javax.swing.JInternalFrame {

    ArrayList<Payroll> payrollArrayList;
    DefaultTableModel temp;
    String titulos[] = {"PAYROLL ID", "CREATION DATE", "MONTH", "PAY DATE", "EMPLOYEE", "BASE SALARY", "TOTAL PLUS", " TOTAL SALARY", "CCSS", "BP", "NET SALARY"};
    SimpleDateFormat hour = new SimpleDateFormat("YYYY");
    int year;
    String month;

    /**
     * Creates new form frmPayroll
     */
    public frmQueryPayroll() {
        initComponents();
    }

    public frmQueryPayroll(frmPayroll aThis, ArrayList<Payroll> payrollArrayList, int pYear, String pMonth) {
        initComponents();
        this.payrollArrayList = payrollArrayList;
        this.month = pMonth;
        this.year = pYear;

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblPayroll = new javax.swing.JTable();

        setClosable(true);
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        tblPayroll.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tblPayroll);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1089, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        if (payrollArrayList.size() > 0) {
            temp = new DefaultTableModel(null, titulos);
            for (int i = 0; i < payrollArrayList.size(); i++) {
                System.out.println(payrollArrayList.get(i).getMonth() + " ----- " + hour.format(payrollArrayList.get(i).getPayDate()) + "  mom:   " + month + "    yer:   " + year);
                if (payrollArrayList.get(i).getMonth().equals(this.month) && hour.format(payrollArrayList.get(i).getPayDate()).equals(String.valueOf(this.year))) {
                    temp.addRow(new Object[]{payrollArrayList.get(i).getIdPayroll(), payrollArrayList.get(i).getCreatrionDate(), payrollArrayList.get(i).getPayDate(),
                        payrollArrayList.get(i).getMonth(), payrollArrayList.get(i).getIdCollaborator().getDNI(),
                        payrollArrayList.get(i).getIdCollaborator().getPosition().getSalary(), payrollArrayList.get(i).getTotalPlus(), payrollArrayList.get(i).getTotalSalary(),
                        payrollArrayList.get(i).getDeductionsCCSS(), payrollArrayList.get(i).getDeductionsBP(), payrollArrayList.get(i).getNetSalary()});
                }
            }
            this.tblPayroll.setModel(temp);
        }else{
        JOptionPane.showConfirmDialog(this, "No results found", "Confirm Message", JOptionPane.DEFAULT_OPTION);
        this.dispose();
        
        
        }
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPayroll;
    // End of variables declaration//GEN-END:variables

}
